const smartphones = [
  {
    name: "iPhone 15 Pro",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-1.jpg",
    buyNew: "https://amzn.to/iphone15pro-nuovo",
    buyRefurbished: "https://amzn.to/iphone15pro-ricondizionato",
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    img: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-ultra-1.jpg",
    buyNew: "https://amzn.to/s24ultra-nuovo",
    buyRefurbished: "https://amzn.to/s24ultra-ricondizionato",
  },
  {
    name: "Google Pixel 8 Pro",
    img: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8-pro-1.jpg",
    buyNew: "https://amzn.to/pixel8pro-nuovo",
    buyRefurbished: "https://amzn.to/pixel8pro-ricondizionato",
  },
  {
    name: "OnePlus 12",
    img: "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12-1.jpg",
    buyNew: "https://amzn.to/oneplus12-nuovo",
    buyRefurbished: "https://amzn.to/oneplus12-ricondizionato",
  },
  {
    name: "Xiaomi 14 Pro",
    img: "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-14-pro-1.jpg",
    buyNew: "https://amzn.to/xiaomi14pro-nuovo",
    buyRefurbished: "https://amzn.to/xiaomi14pro-ricondizionato",
  },
  {
    name: "iPhone 14",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-1.jpg",
    buyNew: "https://amzn.to/iphone14-nuovo",
    buyRefurbished: "https://amzn.to/iphone14-ricondizionato",
  },
  {
    name: "Samsung Galaxy A54",
    img: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a54-5g-1.jpg",
    buyNew: "https://amzn.to/a54-nuovo",
    buyRefurbished: "https://amzn.to/a54-ricondizionato",
  },
  {
    name: "Realme GT 6T",
    img: "https://fdn2.gsmarena.com/vv/pics/realme/realme-gt-6t-1.jpg",
    buyNew: "https://amzn.to/gt6t-nuovo",
    buyRefurbished: "https://amzn.to/gt6t-ricondizionato",
  },
  {
    name: "Motorola Edge 50 Pro",
    img: "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-edge-50-pro-1.jpg",
    buyNew: "https://amzn.to/edge50pro-nuovo",
    buyRefurbished: "https://amzn.to/edge50pro-ricondizionato",
  },
  {
    name: "Honor Magic6 Pro",
    img: "https://fdn2.gsmarena.com/vv/pics/honor/honor-magic6-pro-1.jpg",
    buyNew: "https://amzn.to/magic6pro-nuovo",
    buyRefurbished: "https://amzn.to/magic6pro-ricondizionato",
  },
  {
    name: "iPhone SE (2022)",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-se-2022-1.jpg",
    buyNew: "https://amzn.to/iphonese-nuovo",
    buyRefurbished: "https://amzn.to/iphonese-ricondizionato",
  },
  {
    name: "Nothing Phone (2)",
    img: "https://fdn2.gsmarena.com/vv/pics/nothing/nothing-phone-2-1.jpg",
    buyNew: "https://amzn.to/nothing2-nuovo",
    buyRefurbished: "https://amzn.to/nothing2-ricondizionato",
  },
  {
    name: "Asus ROG Phone 8 Pro",
    img: "https://fdn2.gsmarena.com/vv/pics/asus/asus-rog-phone-8-pro-1.jpg",
    buyNew: "https://amzn.to/rog8pro-nuovo",
    buyRefurbished: "https://amzn.to/rog8pro-ricondizionato",
  },
  {
    name: "Sony Xperia 1 VI",
    img: "https://fdn2.gsmarena.com/vv/pics/sony/sony-xperia-1-vi-1.jpg",
    buyNew: "https://amzn.to/xperia1vi-nuovo",
    buyRefurbished: "https://amzn.to/xperia1vi-ricondizionato",
  },
  {
    name: "Huawei P60 Pro",
    img: "https://fdn2.gsmarena.com/vv/pics/huawei/huawei-p60-pro-1.jpg",
    buyNew: "https://amzn.to/p60pro-nuovo",
    buyRefurbished: "https://amzn.to/p60pro-ricondizionato",
  },
  {
    name: "Telefono Fantasia 16",
    img: "https://example.com/images/phone16.jpg",
    buyNew: "https://amzn.to/phone16-nuovo",
    buyRefurbished: "https://amzn.to/phone16-ricondizionato",
  },
  {
    name: "Telefono Fantasia 17",
    img: "https://example.com/images/phone17.jpg",
    buyNew: "https://amzn.to/phone17-nuovo",
    buyRefurbished: "https://amzn.to/phone17-ricondizionato",
  },
  {
    name: "Telefono Fantasia 18",
    img: "https://example.com/images/phone18.jpg",
    buyNew: "https://amzn.to/phone18-nuovo",
    buyRefurbished: "https://amzn.to/phone18-ricondizionato",
  },
  {
    name: "Telefono Fantasia 19",
    img: "https://example.com/images/phone19.jpg",
    buyNew: "https://amzn.to/phone19-nuovo",
    buyRefurbished: "https://amzn.to/phone19-ricondizionato",
  },
  {
    name: "Telefono Fantasia 20",
    img: "https://example.com/images/phone20.jpg",
    buyNew: "https://amzn.to/phone20-nuovo",
    buyRefurbished: "https://amzn.to/phone20-ricondizionato",
  },
  {
    name: "Telefono Fantasia 21",
    img: "https://example.com/images/phone21.jpg",
    buyNew: "https://amzn.to/phone21-nuovo",
    buyRefurbished: "https://amzn.to/phone21-ricondizionato",
  },
  {
    name: "Telefono Fantasia 22",
    img: "https://example.com/images/phone22.jpg",
    buyNew: "https://amzn.to/phone22-nuovo",
    buyRefurbished: "https://amzn.to/phone22-ricondizionato",
  },
  {
    name: "Telefono Fantasia 23",
    img: "https://example.com/images/phone23.jpg",
    buyNew: "https://amzn.to/phone23-nuovo",
    buyRefurbished: "https://amzn.to/phone23-ricondizionato",
  },
  {
    name: "Telefono Fantasia 24",
    img: "https://example.com/images/phone24.jpg",
    buyNew: "https://amzn.to/phone24-nuovo",
    buyRefurbished: "https://amzn.to/phone24-ricondizionato",
  },
  {
    name: "Telefono Fantasia 25",
    img: "https://example.com/images/phone25.jpg",
    buyNew: "https://amzn.to/phone25-nuovo",
    buyRefurbished: "https://amzn.to/phone25-ricondizionato",
  },
  {
    name: "Telefono Fantasia 26",
    img: "https://example.com/images/phone26.jpg",
    buyNew: "https://amzn.to/phone26-nuovo",
    buyRefurbished: "https://amzn.to/phone26-ricondizionato",
  },
  {
    name: "Telefono Fantasia 27",
    img: "https://example.com/images/phone27.jpg",
    buyNew: "https://amzn.to/phone27-nuovo",
    buyRefurbished: "https://amzn.to/phone27-ricondizionato",
  },
  {
    name: "Telefono Fantasia 28",
    img: "https://example.com/images/phone28.jpg",
    buyNew: "https://amzn.to/phone28-nuovo",
    buyRefurbished: "https://amzn.to/phone28-ricondizionato",
  },
  {
    name: "Telefono Fantasia 29",
    img: "https://example.com/images/phone29.jpg",
    buyNew: "https://amzn.to/phone29-nuovo",
    buyRefurbished: "https://amzn.to/phone29-ricondizionato",
  },
  {
    name: "Telefono Fantasia 30",
    img: "https://example.com/images/phone30.jpg",
    buyNew: "https://amzn.to/phone30-nuovo",
    buyRefurbished: "https://amzn.to/phone30-ricondizionato",
  },// ...aggiungine altri fino a 30 nello stesso formato...
];

export default smartphones;
